CREATE TABLE IF NOT EXISTS teams (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  color TEXT DEFAULT '#3b82f6'
);

CREATE TABLE IF NOT EXISTS laps (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  team_id INTEGER NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
  ts REAL NOT NULL,
  lap_time_sec REAL,
  speed_kmh REAL
);

CREATE INDEX IF NOT EXISTS idx_laps_team ON laps(team_id, ts);
